server:
  port: 18080

# 数据源的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.address}:3306/db_course?useUnicode=true&useSSL=false
    username: root
    password: root123

thrift:
  user:
    ip: user-service
    port: 7911

dubbo:
  application:
    name: course-service
  registry:
    address: zookeeper://${zookeeper.address}:2181
    check: false
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000
