version: '3'

# 启动命令： [emon@emon backend-devops-learning]$ docker-compose up -d
# 查看jar包详情： [emon@emon backend-devops-learning]$ jar -tf user-edge-service/target/user-edge-service.jar
services:
  message-service:
    image: message-service:latest
  user-service:
    image: user-service:latest
    command:
      - "--mysql.address=172.17.0.1"
  user-edge-service:
    image: user-edge-service:latest
    links:
      - user-service
      - message-service
    command:
      - "--redis.address=172.17.0.1"
  course-service:
    image: course-service:latest
    links:
      - user-service
    command:
      - "--mysql.address=172.17.0.1"
      - "--zookeeper.address=172.17.0.1"
  course-edge-service:
    image: course-edge-service:latest
    links:
      - user-edge-service
    command:
      - "--zookeeper.address=172.17.0.1"
  api-gateway-zuul:
    image: api-gateway:latest
    links:
      - user-edge-service
      - course-edge-service
    ports:
      - 8080:8080