#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-web-demo
spec:
  selector:
    matchLabels:
      app: springboot-web-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-web-demo
    spec:
      containers:
      - name: springboot-web-demo
        image: 192.168.200.116:5080/devops-learning/springboot-web-demo:latest
        ports:
        - containerPort: 8080
---
#service
apiVersion: v1
kind: Service
metadata:
  name: springboot-web-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-web-demo
  type: ClusterIP

---
#ingress
#apiVersion: extensions/v1beta1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-web-demo
spec:
  rules:
  - host: springboot.mooc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: springboot-web-demo
            port:
              number: 80

# 执行目录： $ cd /root/dockerdata/backend-devops-learning
# 加载资源： $ kubectl apply -f k8s-demo/springboot-web-demo/springboot-web.yaml
# 删除资源： $ kubectl delete -f k8s-demo/springboot-web-demo/springboot-web.yaml
# 查看deploy： $ kubectl get deploy -o wide
# 查看svc： $ kubectl get svc -o wide
# 查看pod： $ kubectl get pods -o wide
# 查看所有： $ kubectl get all -o wide


# 入额访问？ 192.168.200.118是nginx-ingress-controller所在节点的物理IP地址
# 1：本地配置DNS     192.168.200.118 springboot.mooc.com
# 2：访问：         http://springboot.mooc.com/hello?name=lm
