server:
  port: 8761

eureka:
  server:
    number-of-replication-retries: 1
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: false
    hostname: eureka-server
