server:
  port: 8081
  servlet:
    context-path: /course

dubbo:
  application:
    name: course-edge-service
  registry:
    address: zookeeper://emon:2181
    check: false
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000


user:
  edge:
    service:
      addr: http://127.0.0.1:8082