server:
  port: 8082
  servlet:
    context-path: /user

thrift:
  user:
    ip: 127.0.0.1
    port: 7911
  message:
    ip: 127.0.0.1
    port: 9090

# redis config
spring:
  redis:
    host: emon
    port: 6379
#    password: redis123
    timeout: 0
