FROM 192.168.200.116:5080/devops-learning/openjdk:8-jre
MAINTAINER 问秋 liming2011071@163.com

COPY dockerfiles/springboot-web-demo.jar /springboot-web-demo.jar

ENTRYPOINT ["java", "-jar", "/springboot-web-demo.jar"]
